### ISSUE TITLE
[BUG] Dying in water death loop

### ISSUE THREAD

**Issue by BurnhamR** [MTDOJRP/docs#102]
# In-Game Bug Report

## Description
Dying in water puts you into a death loop

## Steps to Reproduce
1. Enter water
2. Die
3. Die
4. Die
5. Die
6. Die
7. Die
8. Respawn at hospital
9. Die

## Expected Behavior
Revive should put your oxygen level back to full, Put it doesnt causing instant repeated death.

## Screenshots
![image](https://github.com/user-attachments/assets/d99e4a04-9382-4a7e-8158-0acfbd824f09)

## Additional Context
This has been reported multiple times.

## Your Environment
- Windows 11

**Comment by Paneedah** [comment]
Possibly Fixed in Commit: [d4b7c5f](https://github.com/MTDOJRP/KC-Menu/commit/d4b7c5f72c754623d2902d2030659460977c6ecf)
