### ISSUE TITLE
[BUG] Restarting resources flase flag KCAC

### ISSUE THREAD

**Issue by BurnhamR** [MTDOJRP/docs#103]
# In-Game Bug Report

## Description
Sometimes restarting a resource still false flags KCAC

## Expected Behavior
When a resource is restarted by the server it should not flase flag KAC

## Screenshots
![image](https://github.com/user-attachments/assets/b72f1968-2fcb-4428-8f8d-56f4e5b334ba)

## Additional Context
N/A

## Your Environment
- Windows 11

**Comment by Paneedah** [comment]
This isn't because the checks are broken. It's more to do with me being slow at restarting LVC. Dependency script so it auto stops when KC-Menu stops.

I am working on a fix but this is not a high priority item - moving to backlog and assigning low priority.
