### ISSUE TITLE
[FEATURE] Spot Shoter Update

### ISSUE THREAD

**Issue by BurnhamR** [MTDOJRP/docs#104]
# Feature Request

## Feature Description
Shot spotter needs a randomness to it, Currently 1 shot always sets it off. It needs to be like 30% chance a shot sets it off./
As well we need to exempt tasers from settings shot spotter off.

## Problem or Reason
This makes it more realistic and better for LEO

## Additional Context
N/A

## Benefits
This makes it more realistic and better for LEO

**Comment by Paneedah** [comment]
Attempted implementation: [153c65a](https://github.com/MTDOJRP/KC-Menu/commit/153c65a991cd03e327aaabdad59cdf9efda28a5a)
