### ISSUE TITLE
[BUG] False Flag KCAC `/postal`

### ISSUE THREAD

**Issue by BurnhamR** [MTDOJRP/docs#106]
# In-Game Bug Report

## Description
MindVoid ran `/postal` and had somehow triggered the KCAC for updating blip.
He had CAD open then opened the chat and ran the command.

## Steps to Reproduce
Unk

## Expected Behavior
This should not ever flag the AC

## Screenshots
![image](https://github.com/user-attachments/assets/beeab7a5-b7d9-4a1b-b71c-780f5a7d59fb)

## Additional Context
I was unable to replicate, Mindvoid is the user who ran this.

## Your Environment
- Windows 11

**Comment by Paneedah** [comment]
Unable to replicate. MindVoid states that he never even managed to enter the command (only started typing it). I've got no idea what could be causing this. Reference code for blip check:

```js
setTick(() => {
    if (!IsWaypointActive()) {
        lastWaypoint = null;
        return;
    }
    const waypointBlip = ClientUtils.getCurrentWaypointCoords();
    if (waypointBlip === null) {
        lastWaypoint = null;
        return;
    }
    const [x, y, z] = waypointBlip;
    const [lastX, lastY, lastZ] = lastWaypoint || [0.0, 0.0, 0.0];
    if (lastWaypoint && x === lastX && y === lastY && z === lastZ) return;
    if (!IsPauseMenuActive()) {
        const playerPedId = PlayerPedId();
        const vehicle = GetVehiclePedIsIn(playerPedId, false);
        let hasPassenger = false;
        if (vehicle !== 0) {
            for (let i = -1; i < GetVehicleMaxNumberOfPassengers(vehicle); i++) {
                const ped = GetPedInVehicleSeat(vehicle, i);
                if (ped !== 0 && ped !== playerPedId && IsPedAPlayer(ped)) { hasPassenger = true; break; }
            }
            if (!hasPassenger) ClientUtils.flagPlayer('waypoint', 'CT16', { new_coords: `${x}, ${y}, ${z}` });
        }
    }
    lastWaypoint = waypointBlip;
```

If you've got any ideas, let me know.

**Comment by Paneedah** [comment]
Still unable to replicate - mindvoid has given no useful additional information.
