### ISSUE TITLE
[FEATURE] `/ts` cmd (Traffic Stop)

### ISSUE THREAD

**Issue by ibx34** [MTDOJRP/docs#111]
# Feature Request

## Feature Description
Add a CMD `/ts` that creates a traffic stop in the CAD which shows up on the officers and dispatches side of things. You can add things such as location, vehicle description and number of occupants when typing out the command in the sky box. This is very convenient/efficient in not having to open your MDT.

**Comment by BurnhamR** [comment]
I will need to create an endpoint, We could maybe even integrate this with the ALPR? 
Location could be pulled from the postal.

`/ts {desc}`

**Comment by BurnhamR** [comment]
METHOD: `POST` 
PATH: `/v1/call-911`

**Comment by Paneedah** [comment]
Seems to be working as expected now. Moved to `in review` for further testing.

https://discord.com/channels/1132847710282727565/1183144871691833426/1274894325909815366

**Comment by BurnhamR** [comment]
Let's rework this slightly.
1. Add `/tstop` as an alias.

2. Re-format the description.

{UNIT} initiated a traffic stop at {POSTAL} {STREET}{(if plate locked) on 28 {PLATE}}. {ARGUMENTS}

Example if plate locked and w/arguments
1L04 initiated a traffic stop at 1234 San Adreas Ave on 28 12ABC34. Gray 4 Door, Occ x1

Example if only CMD.

1L04 initiated a traffic stop at 1234 San Adreas Ave.

**Comment by Paneedah** [comment]
1. done.
2. not done, but will be done soon

**Comment by Paneedah** [comment]
done
