### ISSUE TITLE
[BUG] Cannot get rid of fuel hose in hand from takner

### ISSUE THREAD

**Issue by OGMindVoid** [MTDOJRP/docs#114]
# In-Game Bug Report

## Description
You cannot drop a fuel hose from a tanker or replace it

## Steps to Reproduce
1. Spawn tanker
2. Fuel aircraft
3. Remove hose

## Expected Behavior
You can replace the hose

## Screenshots
N/A

## Additional Context
N/A

## Your Environment
- Normal instal

---

Please replace the placeholders with the specific details of your bug report. Thank you for helping us improve the game experience!

**Comment by Paneedah** [comment]
We can't do anything about this until I remake the fuel script because it's BigDaddy's and his scripts are all escrowed.
