### ISSUE TITLE
[FEATURE] Fire/EMS Uniform's

### ISSUE THREAD

**Issue by BurnhamR** [MTDOJRP/docs#121]
# Feature Request

## Feature Description
I am opening this issue for @OmegaLeWolf to post and complete all the Fire/EMS Uniforms.

**Comment by OmegaLeWolf** [comment]
## EMS

### Class A
![Class A](https://github.com/user-attachments/assets/d632fb1a-7d50-4bc8-9ffe-b12920e22001)

### Class B
![Class B](https://github.com/user-attachments/assets/20432e5d-b20c-4dbc-b6eb-3959d5ddf286)

### Class C
![Class C](https://github.com/user-attachments/assets/67f942f6-cf1f-41ab-aaf8-8a9c138ddcd9)

### T-Shirt EMT
(This one is so fucking dark....)
![T-Shirt EMT](https://github.com/user-attachments/assets/3b6b6039-9252-49b1-af98-0cd52f8dbf6e) 

## Fire

Same shit but texture changes.

### Class A
![Class A](https://github.com/user-attachments/assets/d632fb1a-7d50-4bc8-9ffe-b12920e22001)

### No Class B

### Class C
![Class C](https://github.com/user-attachments/assets/17d7518e-9d28-4f85-a8d6-07d3c05a809c)

### Turnouts (SCBA)
![Turnouts SCBA](https://github.com/user-attachments/assets/f24e0d03-7d25-4e96-ab96-7020047169f0)

### Turnouts Jacket
![image](https://github.com/user-attachments/assets/82fe1bdf-c455-42d1-92bd-94e3ef1aacf3)



## Supervisors

Supervisors are mostly a couple texture changes with some addons here and there but I want that to be private so people don't try to use uniforms they aren't allowed to use.
