### ISSUE TITLE
[BUG] Disallow players sitting while dragged

### ISSUE THREAD

**Issue by BurnhamR** [MTDOJRP/docs#123]
# In-Game Bug Report

## Description
Disable players being able to sit while being dragged.

Please replace the placeholders with the specific details of your bug report. Thank you for helping us improve the game experience!

**Comment by Paneedah** [comment]
fixed in [94d122a](https://github.com/MTDOJRP/KC-Menu/commit/94d122a883dc069102c04940d3f3bedd41ecc43c)
