### ISSUE TITLE
[FEATURE] Revamped Spawnpoint Locations

### ISSUE THREAD

**Issue by Paneedah** [MTDOJRP/docs#125]
# Feature Request

## Feature Description
We need to go through and create a new set of spawnpoints (as the current ones are a little outdated).

## Additional Context
Here's the current data for it:
```lua
LocationAreas = {
    ['Blaine County'] = {
        blip = { 578.12, 5012.55, 939.34, 3250.00 },
        respawn = {
            { x = 1827.89, y = 3691.76, z = 34.54 },
            { x = -248.47, y = 6331.87, z = 32.87 }
        },
        spawns = {
            { x = -49.69, y = 1961.89, z = 190.21 },
            { x = -280.56, y = 2567.69, z = 72.49 },
            { x = 556.23, y = 2597.21, z = 42.92 },
            { x = 1733.4, y = 3036.5, z = 61.08 },
            { x = 2033.79, y = 3176.7, z = 45.12 },
            { x = 2618.78, y = 3260.51, z = 55.23 },
            { x = 2574.96, y = 4281.95, z = 41.89 },
            { x = 2904.67, y = 4465.58, z = 48.47 },
            { x = 2904.67, y = 4465.58, z = 48.47 },
            { x = 1418.44, y = 4372.85, z = 43.96 },
            { x = 2524.1, y = 2485.22, z = 37.32 },
            { x = -233.21, y = 6443.24, z = 31.2 },
            { x = -10.87, y = 6308.71, z = 31.23 },
            { x = -758.47, y = 5584.04, z = 36.71 },
            { x = -800.53, y = 5401.79, z = 34.21 },
            { x = -718.77, y = 5765.23, z = 17.63 },
            { x = 906.52, y = 3609.64, z = 32.82 }
        }
    },
    ['Sandy Shores'] = {
        blip = { 1653.4, 3542.28, 664.7, 675.00 },
        respawn = {
            { x = 1827.89, y = 3691.76, z = 34.54 }
        },
        spawns = {
            { x = 1733.4, y = 3036.5, z = 61.08 },
            { x = 2033.79, y = 3176.7, z = 45.12 },
            { x = 2574.96, y = 4281.95, z = 41.89 },
            { x = 2904.67, y = 4465.58, z = 48.47 },
            { x = 906.52, y = 3609.64, z = 32.82 }
        }
    },
    ['Paleto Bay'] = {
        blip = { -15.6, 6255.99, 664.7, 1200.00 },
        respawn = {
            { x = -248.47, y = 6331.87, z = 32.87 }
        },
        spawns = {
            { x = -233.21, y = 6443.24, z = 31.2 },
            { x = 416.84, y = 6478.96, z = 28.81 },
            { x = -10.87, y = 6308.71, z = 31.23 },
            { x = -800.53, y = 5401.79, z = 34.21 },
            { x = -758.47, y = 5584.04, z = 36.71 },
            { x = -718.77, y = 5765.23, z = 17.63 }
        }
    },
    ['Grapeseed'] = {
        blip = { 2370.38, 4722.89, 507.83, 805.00 },
        respawn = {
            { x = 1827.89, y = 3691.76, z = 34.54 }
        },
        spawns = {
            { x = 1956.94, y = 4632, z = 40.8 },
            { x = 1418.44, y = 4372.85, z = 43.96 }
        }
    },
    ['Harmony'] = {
        blip = { 601.42, 2732.52, 507.83, 735.00 },
        respawn = {
            { x = 1827.89, y = 3691.76, z = 34.54 }
        },
        spawns = {
            { x = -49.69, y = 1961.89, z = 190.21 },
            { x = -280.56, y = 2567.69, z = 72.49 },
            { x = 556.23, y = 2597.21, z = 42.92 },
            { x = 1733.4, y = 3036.5, z = 61.08 },
            { x = 2033.79, y = 3176.7, z = 45.12 },
            { x = 2524.1, y = 2485.22, z = 37.69 }
        }
    },
    ['Los Santos'] = {
        blip = { -274.63, -358.35, 396.16, 1995.00 },
        respawn = {
            { x = 295.74, y = -1447.04, z = 30.09 },
            { x = -497.03, y = -336.15, z = 35.18 },
            { x = 360.85, y = -584.74, z = 29.13 }
        },
        spawns = {
            { x = -3222.06, y = 1100.48, z = 10.48 },
            { x = 209.26, y = -933.94, z = 30.69 },
            { x = 977.22, y = -228.01, z = 69.69 },
            { x = 624.25, y = 114.56, z = 96.11 },
            { x = 175.72, y = 484.99, z = 142.38 },
            { x = -59.81, y = 118.7, z = 81.5 },
            { x = 1100.5, y = -338.72, z = 67.21 },
            { x = 1241.57, y = -521.25, z = 68.97 },
            { x = 1228.9, y = -1465.01, z = 34.69 },
            { x = 825.2, y = -1156.96, z = 27.81 },
            { x = 709.94, y = -831.57, z = 24.39 },
            { x = -230.97, y = -1703.48, z = 33.98 },
            { x = 165.52, y = -1926.76, z = 21.01 },
            { x = 527.34, y = -1761.18, z = 28.69 },
            { x = -329.55, y = -1334.29, z = 31.28 },
            { x = -1143.61, y = -747.97, z = 20.19 },
            { x = -1652.42, y = -815.56, z = 10.172 },
            { x = -1178.35, y = -1777.79, z = 3.91 },
            { x = -1221.88, y = -1030.54, z = 8.24 }
        }
    },
    ['Fort Zancudo'] = {
        blip = { -2279.39, 3132.97, 183.66, 850.00 },
        respawn = {
            { x = -1847.43, y = 3260.26, z = 33.28 }
        },
        spawns = {
            { x = -1867.58, y = 3259.08, z = 32.82 },
        }
    },
    ['Los Santos Airport'] = {
        blip = { -1146.53, -2665.57, 283.48, 995.00 },
        respawn = {
            { x = -1037.23, y = -2737.01, z = 21.3 }
        },
        spawns = {
            { x = -984.95, y = -2866.59, z = 13.95 },
        }
    },
    ['Vinewood'] = {
        blip = { 82.57, 727.39, 425.03, 965.00 },
        respawn = {
            { x = -497.03, y = -336.15, z = 35.18 },
            { x = 360.85, y = -584.74, z = 29.13 }
        },
        spawns = {
            { x = 977.22, y = -228.01, z = 69.69},
            { x = 624.25, y = 114.56, z = 96.11},
            { x = 175.72, y = 484.99, z = 142.38},
            { x = -59.81, y = 118.7, z = 81.5}
        }
    },
    ['Mirror Park'] = {
        blip = { 992.36, -364.12, 425.03, 669.00 },
        respawn = {
            { x = 360.85, y = -584.74, z = 29.13 }
        },
        spawns = {
            { x = 977.22, y = -228.01, z = 69.69 },
            { x = 624.25, y = 114.56, z = 96.11 },
            { x = 1100.5, y = -338.72, z = 67.21 },
            { x = 1241.57, y = -521.25, z = 68.97 },
            { x = 1228.9, y = -1465.01, z = 34.69 }
        }
    },
    ['South Los Santos'] = {
        blip = { 176.68, -1636.04, 213.38, 650.00 },
        respawn = {
            { x = 295.74, y = -1447.04, z = 30.09 }
        },
        spawns = {
            { x = -230.97, y = -1703.48, z = 33.98 },
            { x = 165.52, y = -1926.76, z = 21.01 },
            { x = 527.34, y = -1761.18, z = 28.69 },
            { x = -329.55, y = -1334.29, z = 31.28 }
        }
    },
    ['Vespucci'] = {
        blip = { -1079.00, -1209.99, 213.38, 625.00 },
        respawn = {
            { x = -497.03, y = -336.15, z = 35.18 }
        },
        spawns = {
            { x = -1143.61, y = -747.97, z = 20.19 },
            { x = -1652.42, y = -815.56, z = 10.2 },
            { x = -1178.35, y = -1777.79, z = 3.91 },
            { x = -1221.88, y = -1030.54, z = 8.24 }
        }
    },
    ['East Los Santos'] = {
        blip = { 1181.65, -1842.19, 213.38, 850.00 },
        respawn = {
            { x = 295.74, y = -1447.04, z = 30.09 }
        },
        spawns = {
            { x = 1228.9, y = -1465.01, z = 34.69 },
            { x = 825.2, y = -1156.96, z = 27.81 },
            { x = 709.94, y = -831.57, z = 24.39 }
        }
    },
    ['Statewide'] = {
        blip = { -281.52, 1989.45, 452.54, 7500.00 },
        respawn = {
            { x = 295.74, y = -1447.04, z = 30.09 },
            { x = -497.03, y = -336.15, z = 35.18 },
            { x = 360.85, y = -584.74, z =  29.13 },
            { x = 1827.89, y = 3691.76, z = 34.54 },
            { x = -248.47, y = 6331.87, z = 32.87 }
        },
        spawns = {
            { x = -49.69, y = 1961.89, z = 190.21 },
            { x = -280.56, y = 2567.69, z = 72.49 },
            { x = -59.81, y = 118.7, z = 81.5 },
            { x = 556.23, y = 2597.21, z = 42.92 },
            { x = 1733.4, y = 3036.5, z = 61.08 },
            { x = 2033.79, y = 3176.7, z = 45.12 },
            { x = 2618.78, y = 3260.51, z = 55.23 },
            { x = 2574.96, y = 4281.95, z = 41.89 },
            { x = 2904.67, y = 4465.58, z = 48.47 },
            { x = 1956.94, y = 4632, z = 40.8 },
            { x = 1418.44, y = 4372.85, z = 43.96 },
            { x = 2524.1, y = 2485.22, z = 44.69 },
            { x = -233.21, y = 6443.24, z = 31.2 },
            { x = 416.84, y = 6478.96, z = 28.81 },
            { x = -10.87, y = 6308.71, z = 31.23 },
            { x = -800.53, y = 5401.79, z = 34.21 },
            { x = -758.47, y = 5584.04, z = 36.71 },
            { x = -718.77, y = 5765.23, z = 17.63 },
            { x = -3222.06, y = 1100.48, z = 10.48 },
            { x = 209.26, y = -933.94, z = 30.69 },
            { x = 977.22, y = -228.01, z = 69.69 },
            { x = 624.25, y = 114.56, z = 96.11 },
            { x = 175.72, y = 484.99, z = 142.38 },
            { x = 1100.5, y = -338.72, z = 67.21 },
            { x = 1228.9, y = -1465.01, z = 34.69 },
            { x = 1241.57, y = -521.25, z = 68.97 },
            { x = 825.2, y = -1156.96, z = 27.81 },
            { x = 709.94, y = -831.57, z = 24.39 },
            { x = -230.97, y = -1703.48, z = 33.98 },
            { x = 165.52, y = -1926.76, z = 21.01 },
            { x = 527.34, y = -1761.18, z = 28.69 },
            { x = -329.55, y = -1334.29, z = 31.28 },
            { x = 906.52, y = 3609.64, z = 32.82 },
            { x = -1143.61, y = -747.97, z = 20.19 },
            { x = -1652.42, y = -815.56, z = 242.01 },
            { x = -1178.35, y = -1777.79, z = 3.91 },
            { x = -1221.88, y = -1030.54, z = 8.24 }
        }
    },
    ['North Blaine County'] = {
        blip = { 578.12, 5012.55, 939.34, 2550.00 },
        respawn = {
            { x = 1827.89, y = 3691.76, z = 34.54 },
            { x = -248.47, y = 6331.87, z = 32.87 }
        },
        spawns = {
            { x = 1733.4, y = 3036.5, z = 61.08 },
            { x = 2033.79, y = 3176.7, z = 45.12 },
            { x = 2618.78, y = 3260.51, z = 55.23 },
            { x = 2574.96, y = 4281.95, z = 41.89 },
            { x = 2904.67, y = 4465.58, z = 48.47 },
            { x = 1956.94, y = 4632, z = 40.8 },
            { x = 1418.44, y = 4372.85, z = 43.96 },
            { x = 2524.1, y = 2485.22, z = 44.69 },
            { x = -233.21, y = 6443.24, z = 31.2 },
            { x = 416.84, y = 6478.96, z = 28.81 },
            { x = -10.87, y = 6308.71, z = 31.23 },
            { x = -800.53, y = 5401.79, z = 34.21 },
            { x = -758.47, y = 5584.04, z = 36.71 },
            { x = -718.77, y = 5765.23, z = 17.63 },
            { x = 906.52, y = 3609.64, z = 32.82 }
        }
    },
    ['Harmony & Sandy Shores'] = {
        blip = { 1319.97, 3106.36, 394.73, 1525.00 },
        respawn = {
            { x = 1827.89, y = 3691.76, z = 34.54 }
        },
        spawns = {
            { x = -49.69, y = 1961.89, z = 190.21 },
            { x = -280.56, y = 2567.69, z = 72.49 },
            { x = 556.23, y = 2597.21, z = 42.92 },
            { x = 1733.4, y = 3036.5, z = 61.08 },
            { x = 2033.79, y = 3176.7, z = 45.12 },
            { x = 2618.78, y = 3260.51, z = 55.23 },
            { x = 2574.96, y = 4281.95, z = 41.89 },
            { x = 906.52, y = 3609.64, z = 32.82 }
        }
    },
    ['Grapeseed & Sandy Shores'] = {
        blip = { 1771.17, 4232.49, 394.73, 1475.00 },
        respawn = {
            { x = 1827.89, y = 3691.76, z = 34.54 }
        },
        spawns = {
            { x = 1733.4, y = 3036.5, z = 61.08 },
            { x = 2033.79, y = 3176.7, z = 45.12 },
            { x = 2574.96, y = 4281.95, z = 41.89 },
            { x = 2904.67, y = 4465.58, z = 48.47 },
            { x = 1956.94, y = 4632, z = 40.8 },
            { x = 906.52, y = 3609.64, z = 32.82 }
        }
    }
}
```

We need to port this over to C# in the future, but for the time being, I rather get this added to Lua side as C# is under heavy dev.

## Benefits
Allows players to have more choice in terms of AOP and spawnpoints to correctly behave (instead of spawning them in the middle of a police station).

---

Please replace the placeholders with the specific details of your feature request. Your contributions help us continuously improve and expand the gaming experience in KCDOJRP!

**Comment by Paneedah** [comment]
Assigned to @BurnhamR

**Comment by BurnhamR** [comment]
Statewide
 Spawn:
    - -745.04144, 5811.24023, 17.53371
    - 416.9968, 6477.44434, 28.80333
    - -235.83215, 6444.33838, 31.19302
    - 287.55768, 6790.5752, 15.70136
    - 1461.19971, 6543.97266, 14.59408
    - 1362.05396, 4325.23145, 38.06487
    - 3323.99048, 5153.97363, 18.32612
    - 2575.30542, 4280.98877, 41.89814
    - 2906.77148, 4465.57617, 48.32421
    - 1670.87134, 4975.55566, 42.30473
    - 388.72293, 3589.40576, 33.2844
    - 905.46503, 3610.83203, 32.81467
    - 2045.97839, 3447.01587, 43.77603
    - 2032.08472, 3177.71216, 45.1982
    - 1730.28064, 3037.16797, 60.84774
    - -283.6048, 2542.22729, 74.53908
    - 1228.33105, 1913.49719, 77.56419
    - 1112.04272, 222.91597, 80.98633
    - 939.80481, 145.12929, 80.82605
    - 1098.32361, -339.04355, 67.21498
    - 1034.32349, -767.11041, 58.00238
    - 1213.32617, -1071.18152, 39.69318
    - 974.87378, -231.6432, 69.38071
    - 625.43878, 143.01297, 95.98666
    - 816.5799, -821.43811, 26.17619
    - 436.52206, 216.69952, 103.1664
    - 176.70586, 387.19977, 109.08505
    - -351.49326, 466.11627, 112.53609
    - -937.36261, 138.30469, 57.33074
    - -816.88214, 48.02832, 48.61785
    - -513.48547, 312.91949, 83.24327
    - 282.06158, 947.88379, 210.77493
    - 265.22867, -178.22968, 61.5709
    - -1371.02747, -470.31668, 23.26584
    - -1646.51208, -195.61375, 55.24543
    - -1316.75183, -249.27211, 42.0832
    - -985.75916, -385.59967, 45.3846
    - -584.73334, -190.67195, 37.87564
    - -570.26172, -443.7128, 34.30948
    - -252.69551, -246.87839, 36.51514
    - -1270.71533, -721.26434, 22.63151
    - -1015.59796, -1351.73755, 5.48664
    - -1178.948, -1776.70056, 3.90222
    - -1031.81116, -837.63666, 19.22926
    - -1598.14246, -863.80896, 10.13043
    - -1225.17017, -1027.62427, 8.19915
    - -896.40997, -779.06396, 15.89994
    - -824.4975, -1221.83252, 7.35879
    - -937.02271, -1524.15405, 5.16529
    - -523.76428, -1799.93823, 22.30757
    - -227.97525, -1700.67285, 33.95818
    - -331.72256, -1353.54419, 31.29572
    - 272.48694, -1620.94678, 31.53629
    - -72.64342, -1832.77783, 26.94667
    - -135.717, -1992.4248, 22.7322
    - -241.63898, -1531.18848, 31.5159
    - 1058.8042, -2446.0293, 28.87753
    - 700.40851, -2253.87769, 29.18821
    - 1196.45203, -1765.07019, 39.22221
    - 851.10547, -1154.39526, 25.27869
    - 925.15332, -1460.02905, 31.01772
    - 168.01498, -759.97699, 32.70922
    - 292.43326, -690.29462, 29.29686
    - 5.89524, -933.99066, 29.90468
    - 379.48126, -903.9826, 29.41875
    - 23.97283, -1100.0509, 38.15686
    - 168.63867, -1086.89197, 29.19759
 Respawn:
    - 293.91962, -1446.44482, 29.966
    - -497.0209, -335.80484, 34.50624
    - -449.99463, -340.89389, 34.49731
    - 361.0509, -584.30347, 28.82252
    - 355.84674, -597.63843, 28.77628
    - 298.3959, -583.68188, 43.25647
    - 1152.04895, -1526.85266, 34.8344
    - 1679.01953, 3655.104, 35.33804
    - 1676.48962, 3661.87012, 35.34447
    - -247.90506, 6331.68506, 32.42262
    - -243.00349, 6326.13379, 32.42716
CayoIsland
 I need you to get this AOP working, Then I will provide the spawn info for it.
BlaineCounty
 Spawn:
    - -745.04144, 5811.24023, 17.53371
    - 416.9968, 6477.44434, 28.80333
    - -235.83215, 6444.33838, 31.19302
    - 287.55768, 6790.5752, 15.70136
    - 1461.19971, 6543.97266, 14.59408
    - 1362.05396, 4325.23145, 38.06487
    - 3323.99048, 5153.97363, 18.32612
    - 2575.30542, 4280.98877, 41.89814
    - 2906.77148, 4465.57617, 48.32421
    - 1670.87134, 4975.55566, 42.30473
    - 388.72293, 3589.40576, 33.2844
    - 905.46503, 3610.83203, 32.81467
    - 2045.97839, 3447.01587, 43.77603
    - 2032.08472, 3177.71216, 45.1982
    - 1730.28064, 3037.16797, 60.84774
    - 871.58478, 2866.4436, 56.8306
    - 171.75449, 3125.81128, 42.32082
    - -283.6048, 2542.22729, 74.53908
    - 1228.33105, 1913.49719, 77.56419
 Respawn:
    - 1679.01953, 3655.104, 35.33804
    - -247.90506, 6331.68506, 32.42262
    - -243.00349, 6326.13379, 32.42716
BlaineCountyNorth
 Spawn:
    - -745.04144, 5811.24023, 17.53371
    - 416.9968, 6477.44434, 28.80333
    - -235.83215, 6444.33838, 31.19302
    - 287.55768, 6790.5752, 15.70136
    - 1461.19971, 6543.97266, 14.59408
    - 1362.05396, 4325.23145, 38.06487
    - 3323.99048, 5153.97363, 18.32612
    - 1670.87134, 4975.55566, 42.30473
 Respawn:
    - -247.90506, 6331.68506, 32.42262
    - -243.00349, 6326.13379, 32.42716
BlaineCountySouth
 Spawn:
    - 2906.77148, 4465.57617, 48.32421
    - 388.72293, 3589.40576, 33.2844
    - 905.46503, 3610.83203, 32.81467
    - 2045.97839, 3447.01587, 43.77603
    - 2032.08472, 3177.71216, 45.1982
    - 1730.28064, 3037.16797, 60.84774
    - 871.58478, 2866.4436, 56.8306
    - 171.75449, 3125.81128, 42.32082
    - -283.6048, 2542.22729, 74.53908
    - 1228.33105, 1913.49719, 77.56419
 Respawn:
    - 1679.01953, 3655.104, 35.33804
    - 1676.48962, 3661.87012, 35.34447
SandyShores
 Spawn:
    - 2575.30542, 4280.98877, 41.89814
    - 2906.77148, 4465.57617, 48.32421
    - 388.72293, 3589.40576, 33.2844
    - 905.46503, 3610.83203, 32.81467
    - 2045.97839, 3447.01587, 43.77603
    - 2032.08472, 3177.71216, 45.1982
 Respawn:
    - 1679.01953, 3655.104, 35.33804
    - 1676.48962, 3661.87012, 35.34447
SandyShoresAndHarmony
 Spawn:
    - 2575.30542, 4280.98877, 41.89814
    - 2906.77148, 4465.57617, 48.32421
    - 388.72293, 3589.40576, 33.2844
    - 905.46503, 3610.83203, 32.81467
    - 2045.97839, 3447.01587, 43.77603
    - 2032.08472, 3177.71216, 45.1982
    - 1730.28064, 3037.16797, 60.84774
    - 871.58478, 2866.4436, 56.8306
    - 171.75449, 3125.81128, 42.32082
    - -283.6048, 2542.22729, 74.53908
    - 1228.33105, 1913.49719, 77.56419
 Respawn:
    - 1679.01953, 3655.104, 35.33804
    - 1676.48962, 3661.87012, 35.34447
SandyShoresAndGrapeseed
 Spawn:
    - 2575.30542, 4280.98877, 41.89814
    - 2906.77148, 4465.57617, 48.32421
    - 1670.87134, 4975.55566, 42.30473
    - 388.72293, 3589.40576, 33.2844
    - 905.46503, 3610.83203, 32.81467
    - 2045.97839, 3447.01587, 43.77603
    - 2032.08472, 3177.71216, 45.1982
 Respawn:
    - 1679.01953, 3655.104, 35.33804
    - 1676.48962, 3661.87012, 35.34447
PaletoBay
 Spawn:
    - -745.04144, 5811.24023, 17.53371
    - 416.9968, 6477.44434, 28.80333
    - -235.83215, 6444.33838, 31.19302
    - 287.55768, 6790.5752, 15.70136
    - 1461.19971, 6543.97266, 14.59408
 Respawn:
    - -247.90506, 6331.68506, 32.42262
    - -243.00349, 6326.13379, 32.42716
Grapeseed
 Spawn:
    - 1362.05396, 4325.23145, 38.06487
    - 3323.99048, 5153.97363, 18.32612
    - 2575.30542, 4280.98877, 41.89814
    - 2906.77148, 4465.57617, 48.32421
    - 1670.87134, 4975.55566, 42.30473
 Respawn:
    - 1679.01953, 3655.104, 35.33804
    - 1676.48962, 3661.87012, 35.34447
Harmony
 Spawn:
    - 2032.08472, 3177.71216, 45.1982
    - 1730.28064, 3037.16797, 60.84774
    - 871.58478, 2866.4436, 56.8306
    - 171.75449, 3125.81128, 42.32082
    - -283.6048, 2542.22729, 74.53908
    - 1228.33105, 1913.49719, 77.56419
 Respawn:
    - 1679.01953, 3655.104, 35.33804
    - 1676.48962, 3661.87012, 35.34447
Vespucci
 Spawn:
    - -1270.71533, -721.26434, 22.63151
    - -1015.59796, -1351.73755, 5.48664
    - -1178.948, -1776.70056, 3.90222
    - -1031.81116, -837.63666, 19.22926
    - -1598.14246, -863.80896, 10.13043
    - -1225.17017, -1027.62427, 8.19915
    - -896.40997, -779.06396, 15.89994
    - -824.4975, -1221.83252, 7.35879
    - -937.02271, -1524.15405, 5.16529
 Respawn:
    - -497.0209, -335.80484, 34.50624
    - -449.99463, -340.89389, 34.49731
LosSantos
 Spawn:
    - 1112.04272, 222.91597, 80.98633
    - 939.80481, 145.12929, 80.82605
    - 1098.32361, -339.04355, 67.21498
    - 1034.32349, -767.11041, 58.00238
    - 1213.32617, -1071.18152, 39.69318
    - 974.87378, -231.6432, 69.38071
    - 625.43878, 143.01297, 95.98666
    - 816.5799, -821.43811, 26.17619
    - 436.52206, 216.69952, 103.1664
    - 176.70586, 387.19977, 109.08505
    - -351.49326, 466.11627, 112.53609
    - -937.36261, 138.30469, 57.33074
    - -816.88214, 48.02832, 48.61785
    - -513.48547, 312.91949, 83.24327
    - 282.06158, 947.88379, 210.77493
    - 265.22867, -178.22968, 61.5709
    - -1371.02747, -470.31668, 23.26584
    - -1646.51208, -195.61375, 55.24543
    - -1316.75183, -249.27211, 42.0832
    - -985.75916, -385.59967, 45.3846
    - -584.73334, -190.67195, 37.87564
    - -570.26172, -443.7128, 34.30948
    - -252.69551, -246.87839, 36.51514
    - -1270.71533, -721.26434, 22.63151
    - -1015.59796, -1351.73755, 5.48664
    - -1178.948, -1776.70056, 3.90222
    - -1031.81116, -837.63666, 19.22926
    - -1598.14246, -863.80896, 10.13043
    - -1225.17017, -1027.62427, 8.19915
    - -896.40997, -779.06396, 15.89994
    - -824.4975, -1221.83252, 7.35879
    - -937.02271, -1524.15405, 5.16529
    - -523.76428, -1799.93823, 22.30757
    - -227.97525, -1700.67285, 33.95818
    - -331.72256, -1353.54419, 31.29572
    - 272.48694, -1620.94678, 31.53629
    - -72.64342, -1832.77783, 26.94667
    - -135.717, -1992.4248, 22.7322
    - -241.63898, -1531.18848, 31.5159
    - 1058.8042, -2446.0293, 28.87753
    - 700.40851, -2253.87769, 29.18821
    - 1196.45203, -1765.07019, 39.22221
    - 851.10547, -1154.39526, 25.27869
    - 925.15332, -1460.02905, 31.01772
    - 168.01498, -759.97699, 32.70922
    - 292.43326, -690.29462, 29.29686
    - 5.89524, -933.99066, 29.90468
    - 379.48126, -903.9826, 29.41875
    - 23.97283, -1100.0509, 38.15686
    - 168.63867, -1086.89197, 29.19759
 Respawn:
    - 293.91962, -1446.44482, 29.966
    - -497.0209, -335.80484, 34.50624
    - -449.99463, -340.89389, 34.49731
    - 361.0509, -584.30347, 28.82252
    - 355.84674, -597.63843, 28.77628
    - 298.3959, -583.68188, 43.25647
    - 1152.04895, -1526.85266, 34.8344
LosSantosCounty
 Spawn:
    - 1112.04272, 222.91597, 80.98633
    - 939.80481, 145.12929, 80.82605
    - 1098.32361, -339.04355, 67.21498
    - 1034.32349, -767.11041, 58.00238
    - 1213.32617, -1071.18152, 39.69318
    - 974.87378, -231.6432, 69.38071
    - 625.43878, 143.01297, 95.98666
    - 816.5799, -821.43811, 26.17619
    - 436.52206, 216.69952, 103.1664
    - 176.70586, 387.19977, 109.08505
    - -351.49326, 466.11627, 112.53609
    - -937.36261, 138.30469, 57.33074
    - -816.88214, 48.02832, 48.61785
    - -513.48547, 312.91949, 83.24327
    - 265.22867, -178.22968, 61.5709
    - -1371.02747, -470.31668, 23.26584
    - -1646.51208, -195.61375, 55.24543
    - -1316.75183, -249.27211, 42.0832
    - -985.75916, -385.59967, 45.3846
    - -584.73334, -190.67195, 37.87564
    - -570.26172, -443.7128, 34.30948
    - -252.69551, -246.87839, 36.51514
    - -1270.71533, -721.26434, 22.63151
    - -1015.59796, -1351.73755, 5.48664
    - -1178.948, -1776.70056, 3.90222
    - -1031.81116, -837.63666, 19.22926
    - -1598.14246, -863.80896, 10.13043
    - -1225.17017, -1027.62427, 8.19915
    - -896.40997, -779.06396, 15.89994
    - -824.4975, -1221.83252, 7.35879
    - -937.02271, -1524.15405, 5.16529
    - -523.76428, -1799.93823, 22.30757
    - -227.97525, -1700.67285, 33.95818
    - -331.72256, -1353.54419, 31.29572
    - 272.48694, -1620.94678, 31.53629
    - -72.64342, -1832.77783, 26.94667
    - -135.717, -1992.4248, 22.7322
    - -241.63898, -1531.18848, 31.5159
    - 1058.8042, -2446.0293, 28.87753
    - 700.40851, -2253.87769, 29.18821
    - 1196.45203, -1765.07019, 39.22221
    - 851.10547, -1154.39526, 25.27869
    - 925.15332, -1460.02905, 31.01772
    - 168.01498, -759.97699, 32.70922
    - 292.43326, -690.29462, 29.29686
    - 5.89524, -933.99066, 29.90468
    - 379.48126, -903.9826, 29.41875
    - 23.97283, -1100.0509, 38.15686
    - 168.63867, -1086.89197, 29.19759
 Respawn:
    - 293.91962, -1446.44482, 29.966
    - -497.0209, -335.80484, 34.50624
    - -449.99463, -340.89389, 34.49731
    - 361.0509, -584.30347, 28.82252
    - 355.84674, -597.63843, 28.77628
    - 298.3959, -583.68188, 43.25647
    - 1152.04895, -1526.85266, 34.8344
LosSantosEast
 Spawn:
    - 1058.8042, -2446.0293, 28.87753
    - 700.40851, -2253.87769, 29.18821
    - 1196.45203, -1765.07019, 39.22221
    - 851.10547, -1154.39526, 25.27869
    - 925.15332, -1460.02905, 31.01772
 Respawn:
    - 293.91962, -1446.44482, 29.966
    - 355.84674, -597.63843, 28.77628
    - 1152.04895, -1526.85266, 34.8344
LosSantosSouth
 Spawn:
    - -523.76428, -1799.93823, 22.30757
    - -227.97525, -1700.67285, 33.95818
    - -331.72256, -1353.54419, 31.29572
    - 272.48694, -1620.94678, 31.53629
    - -72.64342, -1832.77783, 26.94667
    - -135.717, -1992.4248, 22.7322
    - -241.63898, -1531.18848, 31.5159
 Respawn:
    - 293.91962, -1446.44482, 29.966
LosSantosAirport
 Spawn:
    - -983.57672, -2878.46582, 13.9464
 Respawn:
    - -983.57672, -2878.46582, 13.9464
LosSantosDowntown
 Spawn:
    - 265.22867, -178.22968, 61.5709
    - 168.01498, -759.97699, 32.70922
    - 292.43326, -690.29462, 29.29686
    - 5.89524, -933.99066, 29.90468
    - 379.48126, -903.9826, 29.41875
    - 23.97283, -1100.0509, 38.15686
    - 168.63867, -1086.89197, 29.19759
 Respawn:
    - 293.91962, -1446.44482, 29.966
    - -497.0209, -335.80484, 34.50624
    - -449.99463, -340.89389, 34.49731
    - 361.0509, -584.30347, 28.82252
    - 355.84674, -597.63843, 28.77628
    - 298.3959, -583.68188, 43.25647
RockfordHills
 Spawn:
    - -816.88214, 48.02832, 48.61785
    - -1371.02747, -470.31668, 23.26584
    - -1646.51208, -195.61375, 55.24543
    - -1316.75183, -249.27211, 42.0832
    - -985.75916, -385.59967, 45.3846
    - -584.73334, -190.67195, 37.87564
    - -570.26172, -443.7128, 34.30948
    - -252.69551, -246.87839, 36.51514
    - -1270.71533, -721.26434, 22.63151
 Respawn:
    - -497.0209, -335.80484, 34.50624
    - -449.99463, -340.89389, 34.49731
    - 298.3959, -583.68188, 43.25647
FortZancudo
 Spawn:
    - -1848.14038, 3259.70972, 32.82948
 Respawn:
    - -1848.14038, 3259.70972, 32.82948
Vinewood
 Spawn:
    - 625.43878, 143.01297, 95.98666
    - 436.52206, 216.69952, 103.1664
    - 176.70586, 387.19977, 109.08505
    - -351.49326, 466.11627, 112.53609
    - -937.36261, 138.30469, 57.33074
    - -816.88214, 48.02832, 48.61785
    - -513.48547, 312.91949, 83.24327
    - 282.06158, 947.88379, 210.77493
    - 265.22867, -178.22968, 61.5709
 Respawn:
    - -449.99463, -340.89389, 34.49731
    - 361.0509, -584.30347, 28.82252
    - 298.3959, -583.68188, 43.25647
MirrorPark
 Spawn:
    - 939.80481, 145.12929, 80.82605
    - 1112.04272, 222.91597, 80.98633
    - 1098.32361, -339.04355, 67.21498
    - 1034.32349, -767.11041, 58.00238
    - 1213.32617, -1071.18152, 39.69318
    - 974.87378, -231.6432, 69.38071
    - 625.43878, 143.01297, 95.98666
    - 816.5799, -821.43811, 26.17619
 Respawn:
    - 361.0509, -584.30347, 28.82252
    - 355.84674, -597.63843, 28.77628
    - 298.3959, -583.68188, 43.25647
    - 1152.04895, -1526.85266, 34.8344
LittleSeoul
 Remove this AOP option
