### ISSUE TITLE
[FEATURE] KC Announcements

### ISSUE THREAD

**Issue by BurnhamR** [MTDOJRP/docs#152]
# Feature Request

## Feature Description
KC Announcements, a new script that will automatically post announcements on the server in chat

**Comment by Paneedah** [comment]
### 🎉 Task Complete

This task has been completed.
Here's the according documentation for the feature:
- Configurable through `server.cfg`

### Announcer Settings
| Server Variable           | Default Value | Required | Description                                                        |
|:--------------------------|:--------------|:---------|:-------------------------------------------------------------------|
| `kcrp_announcer_enabled`  | `false`       | No       | Whether the announcer is enabled or not                            |
| `kcrp_announcer_interval` | `300`         | No       | The interval in seconds between each announcement                  |
| `kcrp_announcer_type`     | `2`           | No       | Type 1: Picks a random announcement to send every {interval}       |
|                           |               |          | Type 2: Sends announcements in the order provided every {interval} |
| `kcrp_announcer_messages` | `[]`          | Yes?     | The messages to send, e.g. ["Test 1", "Test 2", "Test 3"]          |

### Required Variables
- `Yes`: This variable is required and must be set for the script to even start up.
- `Yes?`: This variable is required if the feature is enabled. If the feature is disabled, the variable does not have to be set.
- `No`: This variable is optional and can be left out if you do not want to use the feature. The default value will be used if the variable is not set.
