### ISSUE TITLE
[KC-Menu] Fire/EMS: Carry Player

### ISSUE THREAD

**Issue by Paneedah** [MTDOJRP/docs#16]
Add the carry function back for Fire/EMS

**Comment by Paneedah** [comment]
### Fixes
- Players disconnecting no longer break and crash the entire system

**Comment by Paneedah** [comment]
### Issue(s) Found
- Carrying sets off anti-cheat for anti-anti-ragdoll.

**Comment by Paneedah** [comment]
### Resolved
- Carrying sets off anti-cheat for anti-anti-ragdoll.
- Stuck in early exit trap when dropping a player

**Comment by Paneedah** [comment]
### Moved to in-review

**Comment by Paneedah** [comment]
### Status Update (To-Do)
Implement a check to make sure the player cannot attack or use the weapon wheel while being carried.

**Comment by Paneedah** [comment]
### Fixed.

You can no longer punch other players while being carried or are carrying someone.

### Moving back to `In-Review` for further testing.

**Comment by BurnhamR** [comment]
Animation is off, Needs some improvement.

**Comment by Paneedah** [comment]
Fixed animation issues
