### ISSUE TITLE
[FEATURE] Welcome Screen

### ISSUE THREAD

**Issue by Paneedah** [MTDOJRP/docs#31]
# Feature Request

## Feature Description
This feature would implement an NUI that displays when the player connects to the server. This screen would allow the player to visualize and modify their characters, select which one to spawn as, and select which area within the AOP they would like to spawn at. We could possibly also add a way to spawn and customize a vehicle (this would be cool as fuck and I'd love to do this).

## Problem or Reason
The reason for this feature would be to streamline the process of a player joining the server for the first time and make it more user-friendly.

## Benefits
This will benefit users as they will be able to easily control their civilians and would give them loads more control over everything that they would want/need to do.

## Additional Context
We could also use this initial screen to force the player towards the CAD and ensure they have a character setup before being able to play. This is debatable however, as it could make the process a little more convoluted.

I would also like to have a way to let the player back into this screen from `KC-Menu` if they would like to.

---

Please replace the placeholders with the specific details of your feature request. Your contributions help us continuously improve and expand the gaming experience in KCDOJRP!

**Comment by BurnhamR** [comment]
I do like this idea, Keeping in Backlog for now.
