### ISSUE TITLE
[BUG] Attempting to drag a player from vehicle failure.

### ISSUE THREAD

**Issue by BurnhamR** [MTDOJRP/docs#34]
# In-Game Bug Report

## Description
Seemingly at random I will be unable to grab a player out of a vehicle using the LEO drag system.
The text above the other players head still shows saying to stop dragging.

## Steps to Reproduce
1. Drag a player
2. Place the player in the back of a LEO vehicle.
3. Attempt to get the player out of the back of a vehicle.

## Expected Behavior
It should just open the door and bring the player out of the vehicle like normal.

## Screenshots
Unaval

## Additional Context
Vehicle door does not open.

## Your Environment
- Windows 11
- Happens in all environments.

---

Please replace the placeholders with the specific details of your bug report. Thank you for helping us improve the game experience!

**Comment by Paneedah** [comment]
### Moved to In-Review

The following commit(s) have been put in place to try and solve this problem:
- [7aad1f9](https://github.com/MTDOJRP/KC-Menu/commit/7aad1f97abeb59bfab7bf220c22da55d11f599c9)
