### ISSUE TITLE
[FEATURE] `/huk` while hands up should go on knees with hands up

### ISSUE THREAD

**Issue by BurnhamR** [MTDOJRP/docs#38]
# Feature Request

## Feature Description
Executing `/huk` while just your hands are up should have your player get onto their knees.

## Problem or Reason
Currently running `/huk` with hands up just puts your hands down.

## Additional Context
Running these through the menu has the same behavior.

## Benefits
This would allow players who have their hands up  go onto their knees which is commonly hands up -> hands up knees.

**Comment by Paneedah** [comment]
You can now utilize `/huk` to get on your knees if your hands are already up.
