### ISSUE TITLE
[BUG/IMPROVEMENT] "Delete Object" message consistency

### ISSUE THREAD

**Issue by BurnhamR** [MTDOJRP/docs#40]
# In-Game Bug Report

## Description
Pressing `Delete Object` in the `Placeable Objects` menu when selecting on "Near" and no objects nearby does not have an output.
However if you have a Radius set it prints out `[Error] No placeable objects found near you`

## Steps to Reproduce
1. Open `Placeable Objects` Menu
2. Select `Delete Object` on Near and a Radius

## Expected Behavior
It should be consistent between the various options, Either no output or always an output.

## Screenshots
![image](https://github.com/MTDOJRP/docs/assets/58826382/43609498-87f0-4e6e-b080-407cc5ad62bb)

## Additional Context
N/A

## Your Environment
- Windows 11

**Comment by Paneedah** [comment]
Decided on completely removing the error message.
