### ISSUE TITLE
[FEATURE] Log staff punishments to #kc-ac-alerts

### ISSUE THREAD

**Issue by BurnhamR** [MTDOJRP/docs#42]
# Feature Request

## Feature Description
When a staff member punishes a player please log it to our #kc-ac-logs

## Problem or Reason
This provides additional logging and alerting for the staff members.

## Additional Context
N/A

## Benefits
This helps staff be in the know of what and when other staff are punishing players.

**Comment by Paneedah** [comment]
![Image](https://github.com/MTDOJRP/docs/assets/76911089/76d8dc88-c337-4b40-96c0-f2bc53f66fd4)

@BurnhamR What is the reason for the existence of this issue? It seems to have been implemented already a while ago.
