### ISSUE TITLE
[FEATURE/IMPROVEMENT] Tackle Keybinding - Controller

### ISSUE THREAD

**Issue by BurnhamR** [MTDOJRP/docs#46]
# Feature Request

## Feature Description
We need to adjust the tackle keybind on controller, I believe it would be best to change it to the attack key(Right Trigger).

## Problem or Reason
Currently it's very difficult to press right d-pad while also sprinting and controlling your character.

## Additional Context
Could we disable punching only on controller if the player is sprinting?
If the player is sprinting and presses attack, it will trigger the tackle system if the player can tackle.

## Benefits
This would make it a lot easier for controller players to tackle.

**Comment by Paneedah** [comment]
### Changes
- Both keyboard and controller no longer need to spam the key (simply holding it down is enough)
- Prevented punching while sprinting for controller users (punching while sprinting results in a tackle (when pressing RT), I believe u can still punch using B)
