### ISSUE TITLE
[BUG] Discord ID Not Found

### ISSUE THREAD

**Issue by Paneedah** [MTDOJRP/docs#49]
# In-Game Bug Report

## Description
Sometimes upon join it'll state that it couldn't find a discord id. Other scripts seem to not have a problem.

## Steps to Reproduce
Join the server.

## Expected Behavior
It not to do that.

## Screenshots
N/A

## Additional Context
N/A

## Your Environment
- Windows 11

**Comment by Paneedah** [comment]
### Potential Fix Impl.

Implemented a new 'dirty marked players' system. This will mark the players as dirty on their connection (if no discord id is found), then this will be re-fetched upon the first heartbeat being received from the player (this is to hopefully give the player enough time to get their identifiers initialized). In addition, implemented a 1000ms delay before starting to fetch identifiers in the first place.

Commit: [6e65dea](https://github.com/MTDOJRP/KC-AntiCheet/commit/6e65dea97b39bcbd995d17429b67412d485df1ac)

**Comment by Paneedah** [comment]
### Potential Implementation / Fix

Modified the existing system to hopefully accommodate and not falsely kick players for 'No Discord ID Found'. This was done in 2 ways.
1. Added a `1,000ms` delay before trying to fetch identifiers.
2. Implemented a system which marks players as 'dirty' when it fails to initially grab their discord id. This will force a re-fetch upon receiving the first heartbeat from the player.

**Action:** Moved to in-review for testing.

**Comment by BurnhamR** [comment]
Still persistent.

**Comment by Paneedah** [comment]
Fix part 1: [8ed6b92](https://github.com/MTDOJRP/KC-AntiCheet/commit/8ed6b92afc1da93da7e9cc1a2535fad6058411e1)

**Comment by Paneedah** [comment]
Fix part 2: [aee3048](https://github.com/MTDOJRP/KC-Menu/commit/aee3048562daebb655cd6f538a49e8f28a72688b)
