### ISSUE TITLE
[FEATURE] BCSO gets SAHP's pants and shoes

### ISSUE THREAD

**Issue by artovz** [MTDOJRP/docs#51]
# Feature Request

## Feature Description
After looking at the clothing line the server offers, and as the Sheriff of BCSO I am requesting to change all pants in the BCSO wardrobe with the SAGP pants and shoes. The IDs are as follows, Legs:25 Shoes:25.

## Problem or Reason
The reason for this change is that it honestly looks much better.

## Additional Context
[image](https://github.com/MTDOJRP/docs/assets/174217650/3bcf1739-088d-4566-9c0c-977254824186)

## Benefits
It provides a more cleaner and professional appearance to my deputies and it looks nicer from someone else's prospective.

---

**Comment by Paneedah** [comment]
Wouldn't implementing this cause confusion between departments? You'd end up having 2 separate departments wearing quite a lot in common.

**Comment by artovz** [comment]
I mean it is only the pants and standard shoes. Wouldn't be a big deal to most.

**Comment by Paneedah** [comment]
Discussed with @BurnhamR, will be making the change at some point in the near future.

**Comment by Paneedah** [comment]
### Pushed

Change has been pushed in commit: [e108eaa](https://github.com/MTDOJRP/KC-Menu/commit/e108eaacaab768f5563ee5d0d006e78e2429ff2f)
