### ISSUE TITLE
[BUG] Ammunition Not Loading (Random)

### ISSUE THREAD

**Issue by BurnhamR** [MTDOJRP/docs#79]
# In-Game Bug Report

## Description
Seemingly randomly the ammunition markers won't spawn and you can't open the ammunitions, No errors in F8 when this happens and it seems to happen to all players at the same time. Restarting the script fixes the issue.

## Steps to Reproduce
As this is random it's difficult to exactly reproduce.
However restarting the server multiple times may cause the issue to appear more frequently.

## Expected Behavior
The ammunition shouldn't be disappearing like this and should always be available for use.

## Additional Context
This may have something to do with KCAC or KC MENU, Unsure, But possibly one of those scripts takes too long to start and causes the issue?
Happens to all ammunitions.

## Your Environment
- Windows 11

**Comment by Paneedah** [comment]
Unable to reproduce the issue.

**Comment by BurnhamR** [comment]
Have we made any changes to attempt to fix or changes that could of fixed? 
`Unable to reproduce` items do not go into in review.
I have had this issue with multiple users and multiple times.

**Comment by Paneedah** [comment]
When was the last time that you've seen this issue? The last user report of this was over 2 weeks ago, with you mentioning that you've also not seen the issue happen again and we even laughed about something else i changed possibly fixing it.

I've also received no additional reports about this issue and wasn't able to replicate this personally.

It seems it could be an issue with an export and the way the runnable thread is made in Ammunation.They simply have a while true loop with no error handling - the moment an error happens on the client (e.g. when restarting KC-Menu), it stops execution.

I could implement a janky fix which basically just prints the error but continues execution if you prefer?

**Comment by BurnhamR** [comment]
Will try to replicate again. Moving back to in-review.
