### ISSUE TITLE
[BUG] Repair trigger issue

### ISSUE THREAD

**Issue by ibx34** [MTDOJRP/docs#80]
# In-Game Bug Report

## Description
Repair trigger at Mirror Park at Auto Repairs is too close to the road. Move into a unique/custom spot. 

## Screenshots
Screenshot attached below. 

![Screenshot 2024-07-24 193735](https://github.com/user-attachments/assets/67a589da-750d-4860-9007-d024e0d273dc)

**Comment by BurnhamR** [comment]
1139.14795, -777.75824, 57.59887

**Comment by Paneedah** [comment]
Updated coordinates to `1139.14795, -777.75824, 57.59887`
