### ISSUE TITLE
[FEATURE] Prevent Spawning Vehicle while Ragdoll

### ISSUE THREAD

**Issue by BurnhamR** [MTDOJRP/docs#97]
# Feature Request

## Feature Description
We need to prevent players from spawning a vehicle while the player is ragdolling

## Problem or Reason
This prevents 2 things, 1. Fail RP, 2. False flagging the Anticheat.

**Comment by Paneedah** [comment]
fixed in commit: [434646d](https://github.com/MTDOJRP/KC-Menu/commit/434646d672c5afc98baba55a52f7ee7271d9c5e0)
