### ISSUE TITLE
[FEATURE] Don't allow re-sapwning upside down vehciles

### ISSUE THREAD

**Issue by BurnhamR** [MTDOJRP/docs#99]
# Feature Request

## Feature Description
We need to prevent players from spawning a vehicle if their current one is flipped.

## Problem or Reason
This prevents a false flag on the KCAC and prevents FRP for people in scenes where they shouldn't of re-spawned the vehicle.

## Additional Context
![image](https://github.com/user-attachments/assets/0575d1ac-79f9-4f0a-8e28-2754ba0beb78)

## Benefits
This prevents a false flag on the KCAC and prevents FRP for people in scenes where they shouldn't of re-spawned the vehicle.

**Comment by Paneedah** [comment]
Possibly fixed in commit: [46300dc](https://github.com/MTDOJRP/KC-Menu/commit/46300dc82ac950ba996a4f4746a58b087859101b)
